Add support for QueryBuilder#TermAt<T> and QueryBuilder#TermAt<T>(int)
BeanCheeseBurrito/Flecs.NET pull request #52
Opened 2024-10-13 00:39 UTC by deathbeam

Add support for TermAt<T> that finds term based on type and type checked term at that asserts term type after finding it at specific index.

Example use:

From:

```cs
        world
            .System<Window, Input, Camera>("UpdateCamera")
            .Kind(Ecs.PostLoad)
            .TermAt(0)
            .Singleton()
            .In()
            .Term()
            .Singleton()
            .In()
            .Term()
            .Singleton()
            .InOut()
            .Each(UpdateCamera);
```

To:

```cs
        world
            .System<Window, Input, Camera>("UpdateCamera")
            .Kind(Ecs.PostLoad)
            .TermAt<Window>()
            .Singleton()
            .In()
            .TermAt<Input>()
            .Singleton()
            .In()
            .TermAt<Camera>()
            .Singleton()
            .InOut()
            .Each(UpdateCamera);
```

2024-10-13 14:22 UTC, BeanCheeseBurrito requested changes
There are some issues when using ``.TermAt`` with pairs. I'm not sure if there is an easy way to check the type of a term in a query builder since the ids can end up in either ``CurrentTerm.id`` ``CurrentTerm.first.id``, ``CurrentTerm.second.id``, or ``CurrentTerm.src.id``.

2024-10-14 09:26 UTC, deathbeam commented on src/Flecs.NET/Core/QueryBuilder.cs
> +        Ecs.Assert(CurrentTerm.first.id == Type<T>.Id(World), "Term type does not match.");
Hmm. So I think i should be checking:

If second.id is set, match second
If second.id is not set, match first

Looking at the code, your first case and second case should have identical behaviour where the second is stored in second.id, and the third one is solved by not checking first if second is set. I will adjust

2024-10-14 10:18 UTC, deathbeam commented on src/Flecs.NET/Core/QueryBuilder.cs
> +        Ecs.Assert(CurrentTerm.first.id == Type<T>.Id(World), "Term type does not match.");
Alright updated + added tests, now it works

2024-10-14 10:47 UTC, deathbeam commented on src/Flecs.NET/Core/QueryBuilder.cs
> +        Ecs.Assert(CurrentTerm.first.id == Type<T>.Id(World), "Term type does not match.");
Also chaged TermAt<T> to Term<T> as it probably makes more sense, and then type checked TermAt<T>(i) stayed the same

2024-10-15 02:13 UTC, BeanCheeseBurrito requested changes
I thought of a few more cases where ``.TermAt`` has incorrect behavior.

The code below should fail because the data type of the term is ``Velocity``. Both ``Velocity`` and ``Position`` are components so the data associated with the pair is a ``Velocity`` value.
```cs
world.QueryBuilder()
    .With<Velocity>().Second<Position>()
    .TermAt<Position>(0)
    .Build();
```
The code below should also fail because the ``Tag`` component has the ``EcsPairIsTag`` trait added to it, indicating that no data is associated with the pair. 
```cs
world.Component<Tag>().Entity.Add(Ecs.PairIsTag);

world.QueryBuilder()
    .With<Tag, Position>()
    .TermAt<Position>(0)
    .Build();
```

2024-10-15 18:58 UTC, deathbeam commented
Ah, that util function is nice. Yea added your new test cases as well, tested it and it looks like it indeed works very well now.

2024-10-16 00:14 UTC, BeanCheeseBurrito approved these changes

2024-10-16 00:15 UTC, merged